apiVersion: v1
kind: Service
metadata:
  name: demo1
spec:
  selector:
    app: demo1
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
spec:
  selector:
    matchLabels:
      app: demo1
  replicas: 3
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
        - name: demo1
          image: k8s-demo1:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kind-nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/demo1(/|$)(.*)" # /demo1 or /demo1/
            backend:
              service:
                name: demo1
                port:
                  number: 8080
