apiVersion: v1
kind: PersistentVolume
metadata:
  name: simod-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/simod-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker
                - kind-worker2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simod-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: simod-volume
  resources:
    requests:
      storage: 2Gi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager-role
  namespace: default
rules:
  - apiGroups: ["", "batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: job-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wq-pub
spec:
  selector:
    matchLabels:
      app: wq-pub
  template:
    metadata:
      labels:
        app: wq-pub
    spec:
      volumes:
        - name: simod-data
          persistentVolumeClaim:
            claimName: simod-volume-claim
      containers:
        - name: publisher
          image: nokal/k8s-samples-wq-publisher:v2
          env:
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: REQUESTS_QUEUE
              value: requests
            - name: RESULTS_QUEUE
              value: results
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: simod-data
              mountPath: /tmp/simod-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wq-work
spec:
  selector:
    matchLabels:
      app: wq-work
  template:
    metadata:
      labels:
        app: wq-work
    spec:
      volumes:
        - name: simod-data
          persistentVolumeClaim:
            claimName: simod-volume-claim
      containers:
        - name: worker
          image: nokal/k8s-samples-wq-worker:v2
          env:
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: REQUESTS_QUEUE
              value: requests
            - name: RESULTS_QUEUE
              value: results
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
