kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: /tmp/simod-volume
        containerPath: /tmp/simod-volume
  - role: worker
    extraMounts:
      - hostPath: /tmp/simod-volume
        containerPath: /tmp/simod-volume
