apiVersion: v1
kind: PersistentVolume
metadata:
  name: simod-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/simod-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker
                - kind-worker2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simod-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: simod-volume
  resources:
    requests:
      storage: 2Gi
