apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: "2023-02-16T20:06:46Z"
  generation: 1
  labels:
    component: rabbitmq
  name: rabbitmq-controller
  namespace: default
  resourceVersion: "827"
  uid: 172f0f03-8101-4abb-b451-348d5a27987e
spec:
  replicas: 1
  selector:
    app: taskQueue
    component: rabbitmq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        imagePullPolicy: Always
        name: rabbitmq
        ports:
        - containerPort: 5672
          protocol: TCP
        resources:
          limits:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
