apiVersion: batch/v1
kind: Job
metadata:
  name: worker
spec:
  completions: 8
  parallelism: 2
  template:
    metadata:
      name: worker
    spec:
      containers:
        - name: c
          image: nokal/k8s-samples-wq-worker:v1
          env:
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: QUEUE
              value: job1
      restartPolicy: OnFailure
